# Generated by Django 4.2.2 on 2023-06-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='category/')),
                ('descciption', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='maincat/')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='product/')),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('product_slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='API.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='maincat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='API.maincat'),
        ),
    ]
